spring.application.name=movie-service
server.port=8082
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/pratice_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
spring.kafka.bootstrap-servers=kafka:19092